status = error
name = default

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}] [%t] %-5level %logger{36} - %msg%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
